MazaoOnline/urls.py
"""MazaoOnline URL Configuration"""
from site_models.views import checkout_page, home_page,OrderSummaryView, ProductDetailView,\
    add_to_cart, CheckoutView, PaymentView, remove_single_item_from_cart, remove_from_cart,\
        ContactView, CashDeliveryView, OrdersView,search_view,product_detail,update_review,\
        add_review,delete_review,order_tracking
from account.views import register_view, login_view, logout_view
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_page, name="home_page"),
    path('', home_page, name="home_page"),
    path('results/', search_view, name="search"),
    path('product/add/', add_review, name="add_review"),
    path('product/<slug>/detail/', product_detail, name="product"),
    path('product/<int:q_id>/delete/', delete_review, name="delete_review"),
    path('order/<int:order_id>/track/', order_tracking, name="order_tracking"),
    path('product/<int:q_id>/<int:user_id>/review/update/', update_review, name="update_review"),
    # path('product/<slug>/detail/', login_required(login_url="login_view")(ProductDetailView.as_view()), name="product"),
    path('add-to-cart/<slug>/', add_to_cart, name="add-to-cart"),
    path('remove-product-from-cart/<slug>/', remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path('remove-from-cart/<slug>/', remove_from_cart, name="remove-from-cart"),
    path('checkout/<int:pk>', checkout_page, name="checkout_page"),
    path('checkout/', login_required(login_url="login_view")(CheckoutView.as_view()), name="checkout"),
    path('contact/', ContactView.as_view(), name="contact"),
    path('delivery/<str:payment_option>/', login_required(login_url="login_view")(CashDeliveryView.as_view()), name="cash-delivery"),
    path('payment/<str:payment_option>/', login_required(login_url="login_view")(PaymentView.as_view()), name="payment"),
    path('order-summary/', login_required(login_url="login_view")(OrderSummaryView.as_view()), name="order-summary"),
    path('all-orders/', login_required(login_url="login_view")(OrdersView.as_view()), name="all-orders"),
    path('register/', register_view, name="register_view"),
    path('log_in/', login_view, name="login_view"),
    path('log_out/', logout_view, name="logout_view"),
    path('', include('account.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, include
from .views import profile_view


urlpatterns = [
    path('profile/<int:id>/view/', profile_view, name='profile')
]

site_models/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=255, null=False)
    price = models.IntegerField(verbose_name="Price(Tshs)")
    description = models.TextField()
    image = models.ImageField(upload_to='products/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={
            "slug": self.slug
            }
        )
    
    def remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            "slug": self.slug
            }
        )

    class Meta:
        verbose_name_plural = 'Products'


class OrderProduct(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f"{self.quantity} {self.product.name}"
    
    def get_total_product_price(self)->int:
        return self.quantity * self.product.price
    
    def total_item_price(self)->int:
        return self.quantity*self.product.price
    
    def get_final_price(self):
        return self.total_item_price()
    


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(OrderProduct)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True, blank=True)
    ordered = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField()


    def __str__(self):
        return f"#{self.id}-Order by {self.customer} - {self.ordered_date.date()}"
    
    def get_total(self)->int:
        total = int()
        for product_order in self.product.all():
            total += product_order.get_total_product_price()
        return total
    
   
class BillingAddress(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    country = CountryField(multiple=False)
    city = models.CharField(max_length=50)
    street_address = models.CharField(max_length=255)
    phone = models.CharField(max_length=13)

    def __str__(self):
        return self.customer.username
    
    class Meta:
        ordering = [
            "-id"
        ]
    

class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    customer = models.ForeignKey(User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return self.customer.username
    
    class Meta:
        ordering = [
            "-id"
        ]

class Contact(models.Model):
    phone = models.CharField(max_length=13, null=True, blank=True)
    message = models.TextField(max_length=500)

    def __str__(self):
        return self.phone


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(max_length=255, null=True)
    rating = models.IntegerField(default=1)
    date_reviewed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"review for {self.product} by {self.user}"


class Store(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)

    def __str__(self):
        return f"{self.name}-{self.location}"


class CurrentOrderStore(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    ordered_product = models.ManyToManyField(Order)
    date_received = models.DateTimeField()

    def __str__(self):
        return f"{self.ordered_product} currently in {self.store}"
    
    class Meta:
        ordering = (
            "-id",
        )
    

templates/base.html
{% include 'header.html' %}
{% block content %}
{% endblock content %}
{% include 'footer.html' %}

templates/cash-delivery.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block content %}

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Pay on deliver</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'home_page' %}">Home</a>
                            <span>Delivery</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <div class="container wow fadeIn">
        <div style="margin-top: 20px;" class="mb-3">
            {% include "messages.html" %}
        </div>
        <!--Grid row-->
        <div class="row" style="margin-top: 20px;">

            <!--Grid column-->
            <div style="margin: auto;" class="col-8 mb-4">

                <!--Card-->
                <div class="card">

                    <form method="POST">
                        {% csrf_token %}
                        <div class="row card-body" style="margin: 10px;">
                            <h4 class="mb-3">Delivery Details</h4>

                            <table class="table table-bordered">
                                <thead>
                                  <tr>
                                    <th scope="col">Firstname</th>
                                    <th scope="col">{{ delivery_address.customer.first_name }}</th>
                                  </tr>
                                </thead>
                                <thead>
                                    <tr>
                                      <th scope="col">Lastname</th>
                                      <th scope="col">{{ delivery_address.customer.last_name }}</th>
                                    </tr>
                                  </thead>
                                  <thead>
                                    <tr>
                                      <th scope="col">Email Address</th>
                                      <th scope="col">{{ delivery_address.customer.email }}</th>
                                    </tr>
                                  </thead>
                                <tbody>
                                  <tr>
                                    <th scope="row">Country</th>
                                    <th scope="row">{{ delivery_address.country.name }}</th>
                                  </tr>
                                </tbody>
                                <tbody>
                                    <tr>
                                      <th scope="row">State/City</th>
                                      <th scope="row">{{ delivery_address.city }}</th>
                                    </tr>
                                </tbody>
                                <tbody>
                                    <tr>
                                      <th scope="row">Physical Address</th>
                                      <th scope="row">{{ delivery_address.street_address }}</th>
                                    </tr>
                                </tbody>
                                <tbody>
                                    <tr>
                                      <th scope="row">Phone Number</th>
                                      <th scope="row">{{ delivery_address.phone }}</th>
                                    </tr>
                                </tbody>
                              </table>
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Confirm</button>
                        </div>
                    </form>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
    {% endblock content %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        MazaoOnline | Log In
    </title>
    <link rel="stylesheet" href="{% static 'css/signin.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <style>
        body {
            background: -webkit-linear-gradient(top, #33537a 0%,#00912b 100%); /* Chrome10+,Safari5.1+ */
        }
    </style>
</head>
<body class="text-center">
    <div class="row">
        <div class="col-12">
            {% include "messages.html" %}
        </div>
        <div class="col-12">
            <form class="form-signin" method="POST">
                {% csrf_token %}
                <!-- <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"> -->
                <h1 style="color: #fff" class="h3 mb-3 font-weight-bolder">Please Log In</h1>
            
                <label for="inputEmail" class="sr-only">Username</label>
                <input type="text" id="inputEmail" class="form-control mb-2" placeholder="Username" name="username" required autofocus>
            
                <label for="inputEmail" class="sr-only">Password</label>
                <input type="password" id="inputEmail" class="form-control" name="password" placeholder="Password" required
                       autofocus>
            
                <button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>
                <p style="color: #fff" class="mt-2 font-weight-bolder">Dont have an account? <a href="{% url 'register_view' %}"><span style="color: #fff;">Sign Up</span></a></p>
                <p style="color: #fff" class="mt-3 mb-3 font-weight-bolder">&copy;MazaoOnline <span id="date"></span></p>
            </form>
            
        </div>
    </div>

</body>
<script type="text/javascript">
    var date = new Date();
    var date_p = document.getElementById("date");
    date_p.innerHTML = date.getFullYear();
</script>
</html>

templates/order_tracking.html
{% extends 'base.html' %}

{% load static %}

{% load humanize %}

{% block custom_css %}
<style>
    .square,
    .btn {
        border-radius: 0px !important;
    }

    /* -- color classes -- */
    .coralbg {
        background-color: #FA396F;
    }

    .coral {
        color: #FA396f;
    }

    .turqbg {
        background-color: #46D8D2;
    }

    .turq {
        color: #46D8D2;
    }

    .white {
        color: #fff !important;
    }

    /* -- The "User's Menu Container" specific elements. Custom container for the snippet -- */
    div.user-menu-container {
        z-index: 10;
        background-color: #fff;
        margin-top: 20px;
        background-clip: padding-box;
        opacity: 0.97;
        filter: alpha(opacity=97);
        -webkit-box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
        box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
    }

    div.user-menu-container .btn-lg {
        padding: 0px 12px;
    }

    div.user-menu-container h4 {
        font-weight: 300;
        color: #8b8b8b;
    }

    div.user-menu-container a,
    div.user-menu-container .btn {
        transition: 1s ease;
    }

    div.user-menu-container .thumbnail {
        width: 100%;
        min-height: 200px;
        border: 0px !important;
        padding: 0px;
        border-radius: 0;
        border: 0px !important;
    }

    /* -- Vertical Button Group -- */
    div.user-menu-container .btn-group-vertical {
        display: block;
    }

    div.user-menu-container .btn-group-vertical>a {
        padding: 20px 25px;
        background-color: #46D8D2;
        color: white;
        border-color: #fff;
    }

    div.btn-group-vertical>a:hover {
        color: white;
        border-color: white;
    }

    div.btn-group-vertical>a.active {
        background: #FA396F;
        box-shadow: none;
        color: white;
    }

    /* -- Individual button styles of vertical btn group -- */
    div.user-menu-btns {
        padding-right: 0;
        padding-left: 0;
        padding-bottom: 0;
    }

    div.user-menu-btns div.btn-group-vertical>a.active:after {
        content: '';
        position: absolute;
        left: 100%;
        top: 50%;
        margin-top: -13px;
        border-left: 0;
        border-bottom: 13px solid transparent;
        border-top: 13px solid transparent;
        border-left: 10px solid #46D8D2;
    }

    /* -- The main tab & content styling of the vertical buttons info-- */
    div.user-menu-content {
        color: #323232;
    }

    ul.user-menu-list {
        list-style: none;
        margin-top: 20px;
        margin-bottom: 0;
        padding: 10px;
        border: 1px solid #eee;
    }

    ul.user-menu-list>li {
        padding-bottom: 8px;
        text-align: center;
    }

    div.user-menu div.user-menu-content:not(.active) {
        display: none;
    }

    /* -- The btn stylings for the btn icons -- */
    .btn-label {
        position: relative;
        left: -12px;
        display: inline-block;
        padding: 6px 12px;
        background: rgba(0, 0, 0, 0.15);
        border-radius: 3px 0 0 3px;
    }

    .btn-labeled {
        padding-top: 0;
        padding-bottom: 0;
    }

    /* -- Custom classes for the snippet, won't effect any existing bootstrap classes of your site, but can be reused. -- */

    .user-pad {
        padding: 20px 25px;
    }

    .no-pad {
        padding-right: 0;
        padding-left: 0;
        padding-bottom: 0;
    }

    .user-details {
        background: #eee;
        min-height: 333px;
    }

    .user-image {
        max-height: 200px;
        overflow: hidden;
    }

    .overview h3 {
        font-weight: 300;
        margin-top: 15px;
        margin: 10px 0 0 0;
    }

    .overview h4 {
        font-weight: bold !important;
        font-size: 40px;
        margin-top: 0;
    }

    .view {
        position: relative;
        overflow: hidden;
        margin-top: 10px;
    }

    .view p {
        margin-top: 20px;
        margin-bottom: 0;
    }

    .caption {
        position: absolute;
        top: 0;
        right: 0;
        background: rgba(70, 216, 210, 0.44);
        width: 100%;
        height: 100%;
        padding: 2%;
        display: none;
        text-align: center;
        color: #fff !important;
        z-index: 2;
    }

    .caption a {
        padding-right: 10px;
        color: #fff;
    }

    .info {
        display: block;
        padding: 10px;
        background: #eee;
        text-transform: uppercase;
        font-weight: 300;
        text-align: right;
    }

    .info p,
    .stats p {
        margin-bottom: 0;
    }

    .stats {
        display: block;
        padding: 10px;
        color: white;
    }

    .share-links {
        border: 1px solid #eee;
        padding: 15px;
        margin-top: 15px;
    }

    .square,
    .btn {
        border-radius: 0px !important;
    }
    #track:hover {
        color: #323232;
    }

    /* -- media query for user profile image -- */
    @media (max-width: 767px) {
        .user-image {
            max-height: 400px;
        }
    }
</style>
{% endblock custom_css %}

{% block content %}

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    {% include "messages.html" %}
    <div class="container">
        <h5 class="mb-3">Order ID: #{{order.id}}</h5>
        <h5 class="mb-3">Delivery Status: {% if order.delivered %}
            <span style="color: green;">Delivered</span> {% else %} <span style="color: red;">Not Delivered</span>
        {% endif %}</h5>
        {% if order.customer == request.user and order.delivered == False%}
        <h5 class="mb-3" style="font-weight: bold;">We're processing your order</h5>
            <a data-toggle="modal" data-target="#exampleModal" href="javascript:void">
                <button class="btn btn-sm btn-success">Confirm Delivery</button>
            </a>
        {% endif %}
        <a href="{% url 'all-orders' %}">
            <button class="float-right btn btn-sm btn-info"><i class="mr-1 fa fa-arrow-left"></i>Back</button>
        </a>
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Location</th>
                <th scope="col">Date Received</th>
              </tr>
            </thead>
            <tbody>
                {% for current in order.currentorderstore_set.all %}
                <tr>
                    <td>{{current.store}}</td>
                    <td>{{current.date_received}}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
          
    </div>
    <!-- Confirm Delivery Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm Delivery</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                {% csrf_token %}
                Confirm Delivery?
                <input type="hidden" name="order" value="{{order.id}}">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Confirm</button>
            </div>
            </div>
            </form>
        </div>
        </div>
    {% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Featured Section Begin -->
    <section class="featured spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>{{ object }} Detail</h2>
                    </div>
                </div>
            </div>
            <!--Grid row-->
            <div class="row wow fadeIn">
                {% include 'messages.html' %}

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <div class="row">
                        <div class="col-12">
                            <img src="{{ object.image.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="col-12 mt-3">
                              <a data-toggle="modal" data-target="#addReviewModal" href="javascript:void(0)" class="btn btn-primary">Add Review</a>
                        </div>
                    </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="">
                                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                            </a>
                        </div>

                        <p class="lead">
                            {% if object.discount_price %}
                            <span class="mr-1">
                                <del>TZS {{ object.price | intcomma }}</del>
                            </span>
                            <span>TZS {{ object.discount_price | intcomma }}</span>
                            {% else %}
                            <span>TZS {{ object.price | intcomma }}</span>
                            {% endif %}
                        </p>

                        <p class="lead font-weight-bold">Description</p>

                        <p>{{ object.description }}</p>

                        {% comment %} <form class="d-flex justify-content-left">
                            <!-- Default input -->
                            <input type="number" value="1" aria-label="Search" class="form-control"
                                style="width: 100px">
                            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                                <i class="fa fa-shopping-cart ml-1"></i>
                            </button>

                        </form> {% endcomment %}
                        <a href="{{ object.add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                            Add to cart
                            <i class="fa fa-shopping-cart ml-1"></i>
                        </a>
                        <a href="{{ object.remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                            Remove from cart
                        </a>
                    </div>
                    {% for q in qs %}
                      <div class="card mb-3">
                        <div class="card-header">
                            Review by: {{q.user}}
                            <br>
                            {{q.date_reviewed}}
                            {% with ''|center:q.rating as range %}
                            {% for _ in range %}
                              <i style="color: yellow;font-size: 28px" title="{{q.rating}} Stars" class="fa fa-star float-right"></i>
                            {% endfor %}
                            {% endwith %}
                        </div>
                        <div class="card-body">
                            <!-- <h5 class="card-title">Special title treatment</h5> -->
                            <p class="card-text">{{q.content}}</p>
                            {% if q.user == request.user %}
                              <a data-toggle="modal" data-target="#exampleModal{{q.id}}" href="javascript:void(0)" class="btn btn-secondary">Edit</a>
                              <a data-toggle="modal" data-target="#exampleModalDelete{{q.id}}" href="javascript:void(0)" class="btn btn-danger">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                        <div class="modal fade" id="exampleModal{{q.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Edit Review</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" action="{% url 'update_review' q.id q.user.id %}">
                                {% csrf_token %}
                                <div class="form-group mt-3">
                                    <label for="message-text" class="col-form-label">Rating <i style="color: yellow;font-size: 28px" class="fa fa-star float-right"></i>:</label>
                                    <input type="number" max="5" name="rating" min="0" value={{q.rating}} class="form-control">
                                </div>
                                <div class="form-group mt-3">
                                    <label for="message-text" class="col-form-label">Content:</label>
                                    <textarea class="form-control" name="content" id="message-text">{{q.content|safe}}</textarea>
                                </div>
                                
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </div>
                            </div>
                            </form>
                        </div>
                        </div>

                        <!-- Delete Modal -->
                        <div class="modal fade" id="exampleModalDelete{{q.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Delete Review</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" action="{% url 'delete_review' q.id %}">
                                {% csrf_token %}
                                Delete Review?
                                <input type="hidden" name="product" value="{{object.id}}">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </div>
                            </div>
                            </form>
                        </div>
                        </div>
                    {% endfor %}
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->
        </div>
    </section>
    <!-- Featured Section End -->

    <!-- Add Review Modal -->
    <div class="modal fade" id="addReviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Review</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form method="POST" action="{% url 'add_review' %}">
        {% csrf_token %}
        <input type="hidden" name="product" value="{{object.id}}">
        <!-- <input type="hidden" name="user" value="{{object.id}}"> -->
        <div class="form-group mt-3">
            <label for="message-text" class="col-form-label">Rating <i style="color: yellow;font-size: 28px" class="fa fa-star float-right"></i>:</label>
            <input type="number" max="5" name="rating" min="0" value="1" class="form-control">
        </div>
        <div class="form-group mt-3">
            <label for="message-text" class="col-form-label">Content:</label>
            <textarea class="form-control" name="content" id="message-text"></textarea>
        </div>
        
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add Review</button>
    </div>
    </div>
    </form>
</div>
</div>

    {% endblock content %}